nome = input('digite aqui algo!')
print(nome)
print('o tipo primitivo é ', type(nome))
print('só tem espassos?', nome.isspace())
print('só tem numeros?', nome.isnumeric())
print('É alfabetico?', nome.isalpha())
print('É alfanumerico?', nome.isalnum())
print('esta em maiuscula?', nome.isupper())
print('esta em minusculos?', nome.islower())
print('esta capitalizada?', nome.istitle())
